version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:stable
    container_name: testifier-nginx
    depends_on:
        - testifier-app
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # generates weather reports
  testifier-app:
    image: albatarnik/testifier:latest
    container_name: testifier-app
    build:
      context: ./
    ports:
      - 8080:8080
    restart: on-failure
